package org.tourandino.model;

// Generated Sep 4, 2015 1:38:42 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
@SuppressWarnings("rawtypes")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3116432396304699263L;
	private Integer roleId;
	private String roleName;
	private String roleDescr;
	private Set users = new HashSet(0);

	public Role() {
	}

	public Role(String roleName) {
		this.roleName = roleName;
	}

	public Role(String roleName, String roleDescr, Set users) {
		this.roleName = roleName;
		this.roleDescr = roleDescr;
		this.users = users;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDescr() {
		return this.roleDescr;
	}

	public void setRoleDescr(String roleDescr) {
		this.roleDescr = roleDescr;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}
	
	public String toString(){
		return this.roleName;
	}

}
